/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    InputBase: typeof import('./src/components/InputBase.vue')['default']
    MaxButton: typeof import('./src/components/MaxButton.vue')['default']
    MaxIcon: typeof import('./src/components/MaxIcon.vue')['default']
    MaxInputText: typeof import('./src/components/MaxInputText.vue')['default']
    MaxPhoneField: typeof import('./src/components/MaxPhoneField.vue')['default']
    TextFormat: typeof import('./src/components/TextFormat.vue')['default']
    TransitionFade: typeof import('./src/components/TransitionFade.vue')['default']
  }
}
