import type { Component } from 'vue';

export const SCENARIO_LOADERS: Record<string, () => Promise<{ default: Component }>> = {
    'inputs-text': () => import('./inputs-text.vue'),
    'inputs-select': () => import('./inputs-select.vue'),
    'inputs-masks': () => import('./inputs-masks.vue'),
    'inputs-toggles': () => import('./inputs-toggles.vue'),
    'inputs-coords': () => import('./inputs-coords.vue'),
    'inputs-files': () => import('./inputs-files.vue'),
    'inputs-special': () => import('./inputs-special.vue'),
    'inputs-rich': () => import('./inputs-rich.vue'),
    'inputs-cards': () => import('./inputs-cards.vue'),
    'inputs-tags': () => import('./inputs-tags.vue'),
    'buttons-main': () => import('./buttons-main.vue'),
    'buttons-confirm': () => import('./buttons-confirm.vue'),
    'buttons-badges': () => import('./buttons-badges.vue'),
    'nav-menus': () => import('./nav-menus.vue'),
    'nav-toolbars': () => import('./nav-toolbars.vue'),
    'nav-side': () => import('./nav-side.vue'),
    'layout-shell': () => import('./layout-shell.vue'),
    'layout-grid': () => import('./layout-grid.vue'),
    'layout-dividers': () => import('./layout-dividers.vue'),
    'data-table': () => import('./data-table.vue'),
    'data-listbox': () => import('./data-listbox.vue'),
    'data-chart': () => import('./data-chart.vue'),
    'data-stats': () => import('./data-stats.vue'),
    'data-pdf': () => import('./data-pdf.vue'),
    'overlays-modal': () => import('./overlays-modal.vue'),
    'overlays-drawer': () => import('./overlays-drawer.vue'),
    'overlays-popover': () => import('./overlays-popover.vue'),
    'overlays-toast': () => import('./overlays-toast.vue'),
    'panels-accordion': () => import('./panels-accordion.vue'),
    'panels-tabs': () => import('./panels-tabs.vue'),
    'media-image': () => import('./media-image.vue'),
    'media-icons': () => import('./media-icons.vue'),
    'media-loaders': () => import('./media-loaders.vue'),
    'media-brand': () => import('./media-brand.vue'),
    'trans-fade': () => import('./trans-fade.vue'),
    'trans-motion': () => import('./trans-motion.vue')
};
