/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimateFade: typeof import('./../src/components/Animations/AnimateFade.vue')['default']
    InputBase: typeof import('./../src/components/InputBase.vue')['default']
    MaxBadgeComponent: typeof import('./../src/components/MaxBadgeComponent.vue')['default']
    MaxButton: typeof import('./../src/components/MaxButton.vue')['default']
    MaxEmptyDiv: typeof import('./../src/components/MaxEmptyDiv.vue')['default']
    MaxGrid: typeof import('./../src/components/MaxGrid.vue')['default']
    MaxGridCols: typeof import('./../src/components/MaxGridCols.vue')['default']
    MaxIcon: typeof import('./../src/components/MaxIcon.vue')['default']
    MaxIconButton: typeof import('./../src/components/MaxIconButton.vue')['default']
    MaxInputAutoComplete: typeof import('./../src/components/MaxInputAutoComplete.vue')['default']
    MaxInputAutoCompleteApi: typeof import('./../src/components/MaxInputAutoCompleteApi.vue')['default']
    MaxInputCep: typeof import('./../src/components/MaxInputCep.vue')['default']
    MaxInputCheckbox: typeof import('./../src/components/MaxInputCheckbox.vue')['default']
    MaxInputCoordinateDecimalLat: typeof import('./../src/components/MaxInputCoordinateDecimalLat.vue')['default']
    MaxInputCoordinateDecimalLng: typeof import('./../src/components/MaxInputCoordinateDecimalLng.vue')['default']
    MaxInputCpfCnpj: typeof import('./../src/components/MaxInputCpfCnpj.vue')['default']
    MaxInputDatePicker: typeof import('./../src/components/MaxInputDatePicker.vue')['default']
    MaxInputField: typeof import('./../src/components/MaxInputField.vue')['default']
    MaxInputFile: typeof import('./../src/components/MaxInputFile.vue')['default']
    MaxInputFileProject: typeof import('./../src/components/MaxInputFileProject.vue')['default']
    MaxInputFileUpload: typeof import('./../src/components/MaxInputFileUpload.vue')['default']
    MaxInputFileUploadBig: typeof import('./../src/components/MaxInputFileUploadBig.vue')['default']
    MaxInputFileUploadButton: typeof import('./../src/components/MaxInputFileUploadButton.vue')['default']
    MaxInputNumber: typeof import('./../src/components/MaxInputNumber.vue')['default']
    MaxInputPhoneMail: typeof import('./../src/components/MaxInputPhoneMail.vue')['default']
    MaxInputRadio: typeof import('./../src/components/MaxInputRadio.vue')['default']
    MaxInputSearch: typeof import('./../src/components/MaxInputSearch.vue')['default']
    MaxInputSelect: typeof import('./../src/components/MaxInputSelect.vue')['default']
    MaxInputSwitch: typeof import('./../src/components/MaxInputSwitch.vue')['default']
    MaxInputText: typeof import('./../src/components/MaxInputText.vue')['default']
    MaxInputTextArea: typeof import('./../src/components/MaxInputTextArea.vue')['default']
    MaxInputToggle: typeof import('./../src/components/MaxInputToggle.vue')['default']
    MaxInputTypeAddress: typeof import('./../src/components/MaxInputTypeAddress.vue')['default']
    MaxLink: typeof import('./../src/components/MaxLink.vue')['default']
    MaxLoader: typeof import('./../src/components/MaxLoader.vue')['default']
    MaxLoaderAi: typeof import('./../src/components/MaxLoaderAi.vue')['default']
    MaxLoaderIcon: typeof import('./../src/components/MaxLoaderIcon.vue')['default']
    MaxLogo: typeof import('./../src/components/MaxLogo.vue')['default']
    MaxMaps: typeof import('./../src/components/MaxMaps.vue')['default']
    MaxMsgLabels: typeof import('./../src/components/MaxMsgLabels.vue')['default']
    MaxPdfView: typeof import('./../src/components/MaxPdfView.vue')['default']
    MaxPhoneField: typeof import('./../src/components/MaxPhoneField.vue')['default']
    MaxTable: typeof import('./../src/components/MaxTable.vue')['default']
    MaxTableData: typeof import('./../src/components/MaxTableData.vue')['default']
    MaxTextInputFloatLabel: typeof import('./../src/components/MaxTextInputFloatLabel.vue')['default']
    MaxTransitionFadeLight: typeof import('./../src/components/MaxTransitionFadeLight.vue')['default']
    MaxTransitionUp: typeof import('./../src/components/MaxTransitionUp.vue')['default']
    MaxUserAvatar: typeof import('./../src/components/MaxUserAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    T1: typeof import('./../src/components/Text/T1.vue')['default']
    T2: typeof import('./../src/components/Text/T2.vue')['default']
    TransitionFade: typeof import('./../src/components/TransitionFade.vue')['default']
  }
}
